apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: stresses.stress.example.com
spec:
  group: stress.example.com
  names:
    kind: Stress
    listKind: StressList
    plural: stresses
    singular: stress
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
